apiVersion: apps/v1
kind: Deployment
metadata:
  name: biggwang-boot
  labels:
    app: biggwang-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: biggwang-boot
  template:
    metadata:
      labels:
        app: biggwang-boot
    spec:
      containers:
        - name: biggwang-boot
          image: boriswinter/biggwang-boot:6.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: biggwang-boot
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30080 # 쿠버네티스에서 자동으로 할당되지 않도록 직접 지정
      targetPort: 8080
  selector:
    app: biggwang-boot